# =============================================================================
# host_vars/server1.yml — Server 1 specific variables
# =============================================================================

# Management IP assigned by Containerlab (see netauto-lab.clab.yml)
ansible_host: 172.20.20.21

# Data-plane address (set via containerlab exec in topology file)
data_interface: eth1
data_ipv4: "192.168.10.10/24"
data_gateway: "192.168.10.1"
