---
- name: Network Configuration Tasks
  hosts: network_nodes
  gather_facts: false
  tasks:

    - name: 1. Configure User Account
      user:
        name: admin
        password: "admin123"
        shell: /bin/bash
        state: present

    - name: 2. Configure Banner Message
      copy:
        dest: /etc/motd
        content: |
          "Authorized access only"|

    - name: 3. Configure Interface Description
      copy:
        dest: 



