---
- name: Verify User Account
  hosts: routers
  gather_facts: no

  tasks:

    - name: Gather Facts
      arista.eos.eos_facts:

    - name: Display hostname
      debug:
        msg: "Checking configured users on {{ ansible_net_hostname }}"